{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csv-processor.fullname" . }}
  labels:
    {{- include "csv-processor.labels" . | nindent 4 }}
  {{- $irsaArn := .Values.aws.irsaRoleArn }}
  {{- if not $irsaArn }}
  {{- if and .Values.aws.accountId .Values.aws.irsaRoleName }}
  {{- $accountId := .Values.aws.accountId -}}
  {{- if kindIs "float64" $accountId -}}
  {{- $accountId = printf "%.0f" $accountId -}}
  {{- else -}}
  {{- $accountId = $accountId | toString -}}
  {{- end -}}
  {{- $irsaArn = printf "arn:aws:iam::%s:role/%s" $accountId .Values.aws.irsaRoleName }}
  {{- end }}
  {{- end }}
  {{- if or $irsaArn .Values.serviceAccount.annotations }}
  annotations:
    {{- if $irsaArn }}
    eks.amazonaws.com/role-arn: {{ $irsaArn | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
