all:
  children:
    kubernetes:
      hosts:
        localhost:
          ansible_connection: local
  vars:
    environment: dev
    s3_bucket: csv-processor-dev
    image_repository: csv-processor
    image_tag: latest
    replica_count: 2
    hpa_min: 2
    hpa_max: 8
